config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  root'pages#home'
  resources :projects

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, :presence => true
  validates :desc, :presence => true
  validates :url, :presence => true

  scope :top_five_most_recent, -> { order(created_at: :desc).limit(5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def error
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  def index
    @projects = Project.all.limit(6)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end
  #
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "You've added #{@project.title} to your projects."
      redirect_to  projects_path
    else
      render :new
    end
  end

  def edit
     @project = Project.find(params[:id])
   end

  def update
    @project= Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:alert] = "You've deleted the #{@project.title} project."
      redirect_to projects_path
    end
  end

private
  def project_params
    params.require(:project).permit(:title, :desc, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioWebsite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render "shared/nav" %>
      <%= render "shared/alerts" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= render "layouts/errors", :object => @project %>

<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :desc %>
  <%= f.text_field :desc %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit  %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<p><%= link_to "Home", projects_path %></p>

app/views/projects/index.html.erb
<h1>My Projects</h1>

<hr>

<ul>
  <% @projects.all %>
</ul>


<% if @projects.any? %>
  <table class="table">
    <head>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>URL Address</th>
      </tr>
    </head>
    <body>
        <% @projects.top_five_most_recent.each do |project| %>
          <tr>
            <td><%= link_to project.title, project_path(project) %></td>
            <td><%= project.desc %></td>
            <td>
              <%if (project.url =~/http/)%><%= link_to project.url, project.url %>
              <%else%><%= link_to "https://#{project.url}", "https://#{project.url}" %><%end%>
            <td>
          </tr>
          <% end %>
        </ul>
        <% else %>
          <p>There are no projects!</p>
        <% end %>
      </body>
    </table>
    <br>
    <h5><%= link_to "Create a new Project", new_project_path %></h5>

app/views/projects/new.html.erb
<h1>Adding new project</h1>

<%= render "form" %>

<p><%= link_to "Home", projects_path %></p>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p><%= link_to "Edit", edit_project_path(@project) %></p>
<p><%= link_to "Delete", project_path(@project),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Go to Projects", projects_path %></p>

app/views/shared/_alerts.html.erb
<%= flash[:alert] %>
<%= flash[:notice] %>

app/views/shared/_nav.html.erb
<div id ="center">
<%= link_to "Home", root_path %>
<%= link_to "Work", projects_path %>

<% if current_user %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <%= link_to "Edit Account", edit_user_registration_path %>

<% else %>
  <%= link_to 'Register', new_user_registration_path %>
  <%= link_to 'Sign In', new_user_session_path %>
<% end %>
</div>